// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytrfoaxwcgonoizrehzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cmZvYXh3Y2dvbm9penJlaHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5OTE2NTYsImV4cCI6MjA1MzU2NzY1Nn0.hLyzx_FZ-2cCsp2RPlR2bFYv3kO6LR3TC6y6PJUmu7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);